# El nombre de nuestro sitio
# va a mostrarse en la barra de navegación superior
name: Bronplast sitio oficial

# Descripción de nuestro sitio
# va a mostrarse en la barra de navegación superior
description:
  Sitio oficial de distribuidora Bronplast

# URL del logo del blog
# va a mostrarse en la barra de navegación superior
avatar: https://raw.githubusercontent.com/negrolio/negrolio.github.io/main/assets/images/logo.svg

# Este valor se usa para generar la navegación interna del sitio
url: https://bronplast.com.ar
